### ISSUE TITLE
Project Part 3

### ISSUE THREAD

**Issue by kylecarlstrom** [TianZhiWang/cmput404-project#107]
- [x] Images uploaded/sent as image/base64
- [x] Images should have authentication
- [x] Able to disable images in admin panel
- [x] Able to disable posts in admin panel
- [x] Docs need to be more specific
- [x] Friends basically everything (check with other teams)
- [x] Friend requests
- [x] Unfriend remote authors
- [x] Get remote friends
- [x] Pull in GitHub stream
- [x] Profile page and update
- [x] Get authors friends (including remote)
- [x] Unlisted posts
- [x] Images endpoint
- [x] Images as blobs, not files

**Comment by kylecarlstrom** [comment]
@joshdeng I think we are complicating unlisted posts. Probably the right thing to do is have our ui be in sync with our front-end. That is the url would reflect where you are in the app (e.g. using React router). However, Hindle basically said the point of unlisted posts is so a user can link to images in markdown. Therefore, he said we can treat unlisted posts as being publicly viewable. This probably means we can just an unlisted option to the dropdown and treat it as {unlisted: true, visibility: PUBLIC}.

**Comment by kylecarlstrom** [comment]
@joshdeng @TianZhiWang 
We have work to do on the front end as well. We need to add a profile page that lists posts of that author and possible has an "Add Friend" button. We also need a friends page that displays a users friends. And optionally a friends request page (or merge into the friends page).

**Comment by kylecarlstrom** [comment]
@joshdeng @TianZhiWang 
Please discuss with each other what parts you are going to be working on so there isn't overlap.
Front-end main points:

- [ ] Profile page
  - [ ] View posts of that author
  - [ ] Add friends
  - [ ] On the backend we will have to use a separate endpoint than in the API so we know which host to ping for foreign authors

- [ ] Friends Page
  - [ ] View friends
  - [ ] View friend requests
  - [ ] Delete friends
  - [ ] Accept friend request
  - [ ] Reject friend requests (likely need to create endpoint on the backend)

- [ ] Create post
  - [ ] Add unlisted option to dropdown (unlisted means visibility: PUBLIC, unlisted: true)
  - [ ] Fix UI so you can create a Post with an Image or Text for content but not both

- [ ] Post List
  - [ ] Better UI for linking to a users profile

**Comment by joshdeng** [comment]
My approach for unlisted Post is to add a query string to shareable url. Which contains post id for a post that is unlisted. (eg. http://127.0.0.1:8080/?id=c5ae48ff-8ff9-4f6e-baf8-f2496bc5347a) Then frontend will send a request to backend for the specific post and display it. And host name is obtained form author object's host.
  The problem is I am not sure how will it work with remote post and whether I get the correct host name or not.

**Comment by joshdeng** [comment]
Also, If unlisted post is set to public, it will be shown in post stream. I don't think that is what we want.

**Comment by kylecarlstrom** [comment]
We can filter out unlisted posts

**Comment by kylecarlstrom** [comment]
Main backend changes:

- [ ] Add ability to update an authors info (PUT)
- [ ] User permissions
  - [ ] Can't delete another authors posts
  - [ ] Can't edit another authors profile info
- [ ] Filter out images to other nodes
- [ ] Filter out posts to other nodes

**Comment by kylecarlstrom** [comment]
@joshdeng @xinyi3 @TianZhiWang @nettapper 
Finishing up:
- [ ]  Friend Request should be deletable
- [ ]  Filter out images to other nodes
- [ ]  Filter out posts to other nodes
- [ ]  Github integration
- [ ] Edit post
  - [ ] Front end: just use a modal or something
  - [ ] Back end: Need PUT for posts
