### ISSUE TITLE
Things still do do

### ISSUE THREAD

**Issue by kylecarlstrom** [TianZhiWang/cmput404-project#68]
- [x] Post visibility - need ability to set author level permissions. Back-end: we need an extra field in the Post model called "visibleTo". Getting posts needs to query for these. Front-end: Mostly hooked up, need a list friends.
- [ ] Post deletion. Author should be able to delete a post. Front-end: Show delete button only for users own post, send a DELETE request to posts/<id>/. Wait for response and remove post.
- [ ] Add friend - Front-end: show a list of users that the current user is not friends with, allow them to follow other users. If we aren't changing the back-end this means we need two network calls: one to get friends and one to get all users. Then we need to filter these into two different groups: friends and others.

That should be enough to get more than half the requirements, don't even need unfriend (and likely don't need post deletion). 

Miscellaneous:
- [ ] API is inconsistent with requirements.txt. Probably should eventually change it. At the very least we NEED to document it.
- [ ] Add more tests
- [ ] Need to deploy to Heroku and make sure everything works

**Comment by nettapper** [comment]
I'm currently working on Post Visibility
